---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/autoking777/argocd-app.git
    targetRevision: HEAD
    path: argocd-app
  destination:
    server: https://kubernetes.default.svc
