---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/autoking777/argocd-app.git
    targetRevision: HEAD
    path: blob/main/application
  destination:
    server: https://kubernetes.default.svc
